import os

env = Environment()
#env = Environment(CXX = 'clang++')
env.Replace(CXX='clang++')
#env.Replace(CXX='c++')


cppflags = ['-g', '-Wall', '-O0']
cpppath = []
libs = []
libpath = []

env.ParseFlags('-g -Wall -O0')

srcs = Glob('*.cpp')

#env.Program('main', srcs, CPPPATH=cpppath, LIBPATH=libpath, LIBS=libs)
env.Program('main', srcs, CPPFLAGS=cppflags, CPPPATH=cpppath, LIBPATH=libpath, LIBS=libs)

env.Alias('install',
		[
			env.Install('/tmp', 'main')
		]
	)

