import os

env = Environment()
#env.Replace(CXX='c++')

MYSQL_INC = '/usr/include/mysql'
MYSQL_LIB = '/usr/lib64/mysql'

cppflags = ['-g', '-Wall', '-O0']
cpppath = ['.', os.getenv('STT_INC'), os.getenv('STT_INC') + '/SttMongoDB', os.getenv('BOOST_INC'), MYSQL_INC]
libs = ['netmsg', 'Common', 'MsgClientLib', 'ServerBase', 'CommonBase', 'MySqlDB', 'SttMongoDB', 'Jsoncpp', 'textlog', 'mongoclient', 'boost_thread', 'boost_chrono', 'boost_system', 'pthread', 'rt', 'boost_regex', 'mysqlclient']
libpath = ['.', os.getenv('STT_LIB'), os.getenv('BOOST_LIB'), MYSQL_LIB]

srcs = Glob('*.cpp')

env.Program('main', srcs, CPPFLAGS=cppflags, CPPPATH=cpppath, LIBPATH=libpath, LIBS=libs)

